# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: golang:latest
stages:
- test
- build
before_script:
- echo "Preparing the tools..."
- apt-get --quiet update --yes
- apt-get --quiet install --yes golang gcc libgl1-mesa-dev xorg-dev xz-utils gcc-mingw-w64-x86-64
  unzip apksigner
- go install fyne.io/fyne/v2/cmd/fyne@latest
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
  | sh -s -- -b $(go env GOPATH)/bin v1.61.0
- golangci-lint --version
- go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
- wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
- unzip android-ndk-r25c-linux.zip
- export ANDROID_NDK_HOME="${PWD}/android-ndk-r25c"
build-job:
  stage: build
  variables:
    SECURE_FILES_DOWNLOAD_PATH: "./"
  script:
  - echo "Getting secure files..."
  - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer"
    | bash
  - echo "Compiling the code..."
  - "./build.sh ${CI_COMMIT_TAG}"
  artifacts:
    paths:
    - EZComm_cmd
    - EZComm_cmd.exe
    - EZComm
    - EZComm_debug
    - EZComm.exe
    - EZComm_debug.exe
    - EZComm.apk
    - EZComm_debug.apk
unit-test-job:
  stage: test
  script:
  - echo "Running unit tests..."
  - go test -cover ./...
lint-test-job:
  stage: test
  script:
  - echo "Linting code... "
  - golangci-lint run
  - gocyclo -over 30 .
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
