package res

import (
	"gitee.com/bon-ami/eztools/v6"
)

// I18nEn initialize resource for en
func I18nEn() {
	eztools.AddLanguage("en", `
		StrURLReadMe = "/-/blob/main/README.md"
		StrEzcName   = "EZComm"
		StrEzpName   = "EZ Project"
		StrInt = "interative"
		StrFil = "files"
		StrDir = "directory"
		StrFilO = "Choose a file below to send. TCP is recommended for transfer of split big files."
		StrCfg = "config"
		StrLcl = "local"
		StrRmt = "remote"
		StrLst = "listen"
		StrLstFl = "Failed to listen. Change local address and port or leave them empty to let system decide."
		StrDis = "disconnect peer"
		StrStp = "stop listening"
		StrCon = "connect"
		StrAdr = "address"
		StrPrt = "port"
		StrRec = "content records"
		StrCnt = "content"
		StrSnd = "send"
		StrTo  = "send to"
		StrFrm = "received from"
		StrFlw = "flow"
		StrStb = "standing by"
		StrAll = "select all"
		StrLogExp  = "export log files"
		StrLang = "languages"
		StrVbs  = "verbose level"
		StrHgh  = "high"
		StrMdm  = "medium"
		StrLow  = "low"
		StrNon  = "none"
		StrFnt      = "fonts"
		StrFnt4Lang = "set this font for this language"
		StrFnt4LangBuiltin = "suggest to use built-in font for this language"
		StrFntRch   = "the quick brown fox jumps over the lazy dog"
		StrReboot4Change     = "restart of this application will show the change"

		StrVer       = "version info"
		StrHlp       = "help info"
		StrV         = "log connection events"
		StrVV        = "also log connetion termination details"
		StrVVV       = "also log I/O details"
		StrLogFn     = "log file name"
		StrCfgFn     = "cfg file name"
		StrFlowFnInf = "input file name to control flow/interactions."

		StrFlowOpenErr   = "flow file opened ERR"
		StrFlowOpenNot   = "flow file NOT opened"
		StrFlowRunning   = "flow file running..."
		StrFlowRunNot    = "flow NOT run"
		StrOK            = "OK"
		StrNG            = "NG"
		StrFlowFinAs     = "flow file finished as "
		StrCut           = "Cut"
		StrCpy           = "Copy"
		StrPst           = "Paste"
		StrCpyAll        = "Copy all"
		StrClr           = "Clear"
		StrListeningOn   = "listening on"
		StrConnFail      = "fail to connect to "
		StrConnected     = "connected"
		StrDisconnected  = "disconnected"
		StrNotInRec      = "NOT in record!"
		StrSvrIdle       = "server idle"
		StrClntLft       = "clients left"
		StrNoPeer4       = "NO peer found for"
		StrDisconnecting = "disconnecting"
		StrStopLstn      = "stopped listening"
		StrFl2Rcv        = "failed to receive"
		StrGotFromSw     = "got from somewhere"
		StrGotFrom       = "got from"
		StrUnknownDsc    = "UNKNOWN peer disconnected"
		StrFl2Snd        = "failed to send"
		StrSw            = "somewhere"
		StrSnt2          = "sent to"
		StrInfLog        = "log"
		StrAntiFld       = "Anti Attack"
		StrLmt = "Limit per second"
		StrPrd = "Period of refusal"
		StrTooLarge2Rcv = "too large to receive by UDP"
		StrFileAwareness= "File awareness needed for output"
		StrFileSave     = "Choose following file in next step to allow output"
		StrInfLan       = "LAN"
		StrPokePeer     = "Look for a peer"
		StrDiscoverFail = "Discovery Failed"
		StrAlert        = "Alert"
		StrNoPerm       = "No permission"
		StrRcvFil       = "Received files"
		StrDownloads    = "Downloads"
		StrExp          = "export"
		StrRmAll        = "remove all these files?"
		StrDel          = "delete"
		StrCopied       = "Copied"
		StrHeader       = "Header"
		StrValue        = "Value"
		StrSE2Del       = "([Shift]+)[Enter] to remove"
		StrTxt2ShareBtCS= "text to share between client and server"
		StrLanHint      = "Click one below to copy a local address to paste in a browser"
	`)
}
