package res

import (
	"gitee.com/bon-ami/eztools/v6"
)

// I18nJa initialize resource for ja
func I18nJa() {
	eztools.AddLanguage("ja", `
		StrURLReadMe = "/-/blob/main/README.md"
		StrEzcName   = "EZコム"
		StrEzpName   = "EZ プロジェクト"
		StrInt = "インターマティブ"
		StrFil = "ファイル"
		StrDir = "フォルダ"
		StrFilO = "送信するファイルを以下に選択してください。TCPは、分割された大きなファイルの転送に推奨されます。"
		StrCfg = "設定"
		StrLcl = "ローカル"
		StrRmt = "リモート"
		StrLst = "聞く"
		StrLstFl = "リッスンできませんでした。ローカルアドレスとポートを変更するか、空のままにしてシステムに決定させます。"
		StrDis = "ピアの切断"
		StrStp = "リスニングを停止"
		StrCon = "接続"
		StrAdr = "アドレス"
		StrPrt = "ポート"
		StrRec = "コンテンツレコード"
		StrCnt = "コンテンツ"
		StrSnd = "送信"
		StrTo = "送信先"
		StrFrm = "受信元"
		StrFlw = "フロー"
		StrStb = "スタンバイ"
		StrAll = "すべて選択"
		StrLogExp  = "ログ・ファイルのエクスポート"
		StrLang = "言語"
		StrVbs  = "詳細レベル"
		StrHgh  = "高い"
		StrMdm  = "ミディアム"
		StrLow  = "低い"
		StrNon  = "なし"
		StrFnt      = "フォント"
		StrFnt4Lang = "この言語にこのフォントを設定する"
		StrFnt4LangBuiltin = "この言語に組み込みフォントを使用することを提案する"
		StrFntRch = "こんにちは世界"
		StrReboot4Change = "このアプリケーションを再起動すると変更が表示されます"

		StrVer = "バージョン情報"
		StrHlp = "ヘルプ情報"
		StrV = "接続イベントをログに記録する"
		StrVV = "接続終了の詳細もログに記録する"
		StrVVV = "入出力の詳細もログに記録する"
		StrLogFn = "ログ ファイル名"
		StrCfgFn = "設定ファイル名"
		StrFlowFnInf = "フロー/インタラクションを制御するための入力ファイル名"

		StrFlowOpenErr = "フロー ファイルがエラーで開かれました"
		StrFlowOpenNot = "フローファイルが開かれていません"
		StrFlowRunning = "フロー ファイル ランニング中..."
		StrFlowRunNot = "フローが実行されない"
		StrOK = "OK"
		StrNG = "NG"
		StrFlowFinAs     = "フローファイルは次のように終了しました"
		StrCut = "カット"
		StrCpy = "コピー"
		StrPst = "貼り付け"
		StrCpyAll = "すべてコピー"
		StrClr = "クリア"

		StrListeningOn   = "聞いている"
		StrConnFail      = "に接続できません"
		StrConnected     = "接続済み"
		StrDisconnected  = "切断"
		StrNotInRec      = "記録にない!"
		StrSvrIdle       = "サーバーがアイドル状態"
		StrClntLft       = "クライアントが去った"
		StrNoPeer4       = "ピアが見つかりません"
		StrDisconnecting = "切断中"
		StrStopLstn      = "聞くのをやめた"
		StrFl2Rcv        = "受信に失敗しました"
		StrGotFromSw     = "どこかから来た"
		StrGotFrom       = "から得た"
		StrUnknownDsc    = "不明なピアが切断されました"
		StrFl2Snd        = "送信に失敗しました"
		StrSw            = "どこかで"
		StrSnt2          = "送信先"
		StrInfLog        = "ログ"
		StrAntiFld       = "アンチアタッ"
		StrLmt = "1 秒あたりの制限"
		StrPrd = "拒絶期間"
		StrTooLarge2Rcv  = "大きすぎて UDP で受信できない"
		StrFileAwareness = "出力に必要なファイル認識"
		StrFileSave     = "出力を許可するには、次の手順で次のファイルを選択してください"
		StrInfLan       = "LAN"
		StrPokePeer     = "ピアを探す"
		StrDiscoverFail = "検出に失敗しました"
		StrAlert        = "アラート"
		StrNoPerm       = "権限なし"
		StrRcvFil       = "受信したファイル"
		StrDownloads    = "ダウンロード"
		StrExp          = "エクスポート"
		StrRmAll        = "これらすべてのファイルを削除しますか?"
		StrDel          = "削除"
		StrCopied       = "コピー済み"
		StrHeader       = "メッセージ ヘッダー"
		StrValue        = "数値"
		StrSE2Del       = "([Shift]+)[Enter]削除"
		StrTxt2ShareBtCS= "クライアントとサーバー間で共有するテキスト"
		StrLanHint      = "ブラウザに貼り付けるローカルアドレスをコピーするには、以下をクリックしてください"
	`)
}
