package res

import (
	"gitee.com/bon-ami/eztools/v6"
)

// I18nEs initialize resource for es
func I18nEs() { // by bing.com
	eztools.AddLanguage("es", `
		StrURLReadMe = "/-/blob/main/README.md"
		StrEzcName   = "EZComm"
		StrEzpName   = "EZ Project"
		StrInt = "interacción"
		StrFil = "archivo"
		StrDir = "carpeta"
		StrFilO = "Elija un archivo a continuación para enviar. TCP se recomienda para la transferencia de archivos grandes divididos."
		StrCfg = "configuración"
		StrLcl = "local"
		StrRmt = "remoto"
		StrLst = "escuchar"
		StrLstFl = "No se escuchó. Cambie la dirección local y el puerto o déjelos vacíos para que el sistema decida."
		StrDis = "desconectar del mismo nivel"
		StrStp = "dejar de escuchar"
		StrCon = "conectar"
		StrAdr = "dirección"
		StrPrt = "puerto"
		StrRec = "registros de contenido"
		StrCnt = "contenido"
		StrSnd = "enviar"
		StrTo  = "enviar a"
		StrFrm = "recibido de"
		StrFlw = "fluir"
		StrStb = "esperando"
		StrAll = "seleccionar todo"
		StrLogExp  = "Exportar archivos de registro"
		StrLang = "Idiomas"
		StrVbs  = "nivel detallado"
		StrHgh  = "alto"
		StrMdm  = "medio"
		StrLow  = "bajo"
		StrNon  = "ninguno"
		StrFnt      = "fuentes"
		StrFnt4Lang = "establecer esta fuente para este idioma"
		StrFnt4LangBuiltin = "Le recomendamos que utilice fuentes integradas para este idioma"
		StrFntRch   = "the quick brown fox jumps over the lazy dog"
		StrReboot4Change     = "el reinicio de esta aplicación mostrará el cambio"

		StrVer       = "información de la versión"
		StrHlp       = "información de ayuda"
		StrV         = "Registrar eventos de conexión"
		StrVV        = "También registre los detalles de terminación de la conexión"
		StrVVV       = "También registre los detalles de E/S"
		StrLogFn     = "nombre del archivo de registro"
		StrCfgFn     = "nombre del archivo de configuración"
		StrFlowFnInf = "nombre del archivo de entrada para controlar el flujo/las interacciones."

		StrFlowOpenErr   = "error de archivo de flujo abierto"
		StrFlowOpenNot   = "archivo de flujo NO abierto"
		StrFlowRunning   = "archivo de flujo en ejecución"
		StrFlowRunNot    = "flujo NO ejecutado"
		StrOK            = "De acuerdo"
		StrNG            = "Mal"
		StrFlowFinAs     = "archivo de flujo terminado como"
		StrCut           = "Cortar"
		StrCpy           = "Copiar"
		StrPst           = "Pegar"
		StrCpyAll        = "Copiar todo"
		StrClr           = "Claro"
		StrListeningOn   = "escuchar en"
		StrConnFail      = "No se puede conectar a"
		StrConnected     = "conexo"
		StrDisconnected  = "desconectado"
		StrNotInRec      = "NO está registrado!"
		StrSvrIdle       = "servidor inactivo"
		StrClntLft       = "clientes abandonados"
		StrNoPeer4       = "NO se encontró un par para"
		StrDisconnecting = "desconectar"
		StrStopLstn      = "dejó de escuchar"
		StrFl2Rcv        = "error al recibir"
		StrGotFromSw     = "llegó de algún lugar"
		StrGotFrom       = "obtenido de"
		StrUnknownDsc    = "DESCONOCIDO par desconectado"
		StrFl2Snd        = "error al enviar"
		StrSw            = "algún lado"
		StrSnt2          = "enviado a"
		StrInfLog        = "registro"
		StrAntiFld       = "Antiataque"
		StrLmt = "Límite por segundo"
		StrPrd = "Plazo de denegación"
		StrTooLarge2Rcv  = "demasiado grande para recibir por UDP"
		StrFileAwareness = "Reconocimiento de archivos necesario para la salida"
		StrFileSave     = "Elija el siguiente archivo en el siguiente paso para permitir la salida"
		StrInfLan       = "LAN"
		StrPokePeer     = "Buscar un compañero"
		StrDiscoverFail = "Error de descubrimiento"
		StrAlert        = "Alerta"
		StrNoPerm       = "sin permiso"
		StrRcvFil       = "Archivos recibidos"
		StrDownloads    = "Descargas"
		StrExp          = "exportar"
		StrRmAll        = "¿eliminar todos estos archivos?"
		StrDel          = "borrar"
		StrCopied       = "Copiado"
		StrHeader       = "Encabezado de mensaje"
		StrValue        = "Valor"
		StrSE2Del       = "([Mayús]+)[Entrar] para eliminar"
		StrTxt2ShareBtCS= "texto para compartir entre el cliente y el servidor"
		StrLanHint      = "Haga clic en uno de abajo para copiar una dirección local para pegarla en un navegador"
	`)
}
