package res

import (
	"gitee.com/bon-ami/eztools/v4"
)

func I18nZhtw() {
	eztools.AddLanguage("zh-TW", `
		StrInt = "交互"
		StrFil = "文件"
		StrDir = "資料夾"
		StrFilO = "在下面選擇要發送的檔。建議使用TCP來確保傳輸拆分的大檔。"
		StrDirI = "在下面選擇一個資料夾以保存收到的檔。"
		StrCfg = "配置"
		StrLcl = "當地"
		StrRmt = "遠端"
		StrLst = "監聽"
		StrDis = "斷開對端"
		StrStp = "停止收聽"
		StrCon = "連接"
		StrAdr = "位址"
		StrPrt = "埠"
		StrRec = "內容記錄"
		StrCnt = "內容"
		StrSnd = "發送"
		StrTo  = "發送到"
		StrFrm = "接收於"
		StrFlw = "流程"
		StrStb = "待命"
		StrAll = "全選"
		StrLog  = "日誌檔"
		StrLang = "語言"
		StrVbs  = "日誌級別"
		StrHgh  = "高"
		StrMdm  = "中"
		StrLow  = "少"
		StrNon  = "無"
		StrFnt      = "字體"
		StrFnt4Lang = "為此語言設置此字體"
		StrFnt4LangBuiltin = "建議為此語言使用內置字體"
		StrFntRch   = "世界你好"
		StrReboot4Change     = "應用重新啟動後變化生效"

		StrVer       = "版本資訊"
		StrHlp       = "幫助資訊"
		StrV         = "記錄連接事件"
		StrVV        = "並記錄斷連詳情"
		StrVVV       = "再記錄收發詳情"
		StrLogFn     = "日誌檔名"
		StrCfgFn     = "設置檔名"
		StrFlowFnInf = "輸入檔名能控制流程"

		StrFlowOpenErr   = "打開流程文件出錯"
		StrFlowOpenNot   = "未打開流程檔"
		StrFlowRunning   = "正在運行流程"
		StrFlowRunNot    = "流程未運行"
		StrOK            = "通過"
		StrNG            = "錯誤"
		StrFlowFinAs     = "流程結束為"
		StrCut           = "剪切"
		StrCpy           = "拷貝"
		StrPst           = "粘貼"
		StrCpyAll        = "拷貝所有"
		StrClr           = "清空"
		StrListeningOn   = "監聽於"
		StrConnFail      = "無法連接到"
		StrConnected     = "已連接"
		StrDisconnected  = "已斷連"
		StrNotInRec      = "不在記錄中"
		StrSvrIdle       = "伺服器空閒"
		StrClntLft       = "剩餘用戶端"
		StrNoPeer4       = "找不到對應對端"
		StrDisconnecting = "正在斷連"
		StrStopLstn      = "已停止監聽"
		StrFl2Rcv        = "無法收取"
		StrGotFromSw     = "收自某處"
		StrGotFrom       = "收自"
		StrUnknownDsc    = "未知對端斷連"
		StrFl2Snd        = "無法發送"
		StrSw            = "某處"
		StrSnt2          = "已發送到"
		StrInfLog        = "日誌"
		StrAntiFld       = "反攻擊"
		StrLmt = "每秒限制"
		StrPrd = "駁回期限"
		StrTooLarge2Rcv = "太大，無法由UDP接收"
	`)
}
